### ISSUE TITLE
Add combobox to select ethernet device

### ISSUE THREAD

**Issue by norihiro** [norihiro/obs-h8819-source#2]

**Comment by Yttrium-tYcLief** [comment]
It might be better practice to use the custom adapter name, rather than the device name.

![image](https://user-images.githubusercontent.com/1037011/192158318-a6e42b22-8099-4f50-a5c4-c7f346f42fb4.png)
![image](https://user-images.githubusercontent.com/1037011/192158339-7a6de429-eab9-4f75-9e06-0a1287654d13.png)

(in this instance, the label in OBS should probably say "Ethernet 2")

It might not make as much sense on the back-end, but is probably more useful for end-users when they have a large number of identical device IDs. I might be wrong but I think this hierarchy still makes sense, considering the Npcap driver is hooked through this adapter, rather than directly to the device:

![image](https://user-images.githubusercontent.com/1037011/192158671-5a488926-2af0-4b63-b8f9-919987fe661f.png)

**Comment by norihiro** [comment]
> It might be better practice to use the custom adapter name, rather than the device name.

The displayed name is what npcap library returned.
Fortunately, Wireshark has a workaround to show user-friendly names and the code is under GPL 2+ so that I can copy the code.

https://gitlab.com/wireshark/wireshark/-/blob/master/capture/capture-pcap-util.c#L466-501

`get_windows_interface_friendly_name` in `capture/capture_win_ifnames.c` has the same implementation. I should call the function.
